### ISSUE TITLE
How do you generate the `adtgen.js` executable?

### ISSUE THREAD

**Issue by idkjs** [ahrefs/atdgen-workshop-starter#4]
Im trying to using this somewhere else and wondering how you would get the `atdgen.js` code. Running `atgen -bs file` doesnt work on its own apparently as noted https://github.com/ahrefs/bs-atdgen-codec-runtime/issues/7#issue-438283996

**Comment by Khady** [comment]
```bash
git clone git@github.com:mjambon/atd.git
cd atd/
dune build atdgen/bin/ag_main.bc.js --profile=release
cp _build/default/atdgen/bin/ag_main.bc.js atdgen.js
```

**Comment by idkjs** [comment]
Do you do that in the same directory as the project you are using it in?

**Comment by Khady** [comment]
Usually no. Once you have the atdgen.js file, you can move it everywhere, run it the way you want. It's like a usual binary except you need nodejs to run it.

**Comment by idkjs** [comment]
@Khady thank you, sir.
